### ISSUE TITLE
soiltestcorr

### ISSUE THREAD

**Issue by adriancorrendo** [IdahoAgStats/ctv-agriculture#11]
1. Which package would you like to suggest? What features does it provide?
soiltestcorr is a compilation of functions designed to assist users on the correlation analysis of crop yield and soil test values.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=soiltestcorr

3. Which category do you think is the best fit for the package:
Soil Science

**Comment by adriancorrendo** [comment]
soiltestcorr includes functions to estimate response patterns to nutrient availability and critical soil test values using alternative approaches such as: 
1) the modified arcsine-log calibration curve (Correndo et al., 2017) <https://doi.org/10.1071%2FCP16444>; 
2) the graphical Cate-Nelson quadrants-analysis (Cate & Nelson, 1965), 
3) the statistical Cate-Nelson quadrants-analysis (Cate & Nelson, 1971) <https://doi.org/10.2136%2Fsssaj1971.03615995003500040048x>, 
4) the linear-plateau regression (Anderson & Nelson, 1975) <https://doi.org/10.2307%2F2529422>, 
5) the quadratic-plateau regression (Bullock & Bullock, 1994) <https://doi.org/10.2134%2Fagronj1994.00021962008600010033x>, and 
6) the Mitscherlich regression (Melsted & Peck, 1977) <https://doi.org/10.2134%2Fasaspecpub29.c1>.

**Comment by jpiaskowski** [comment]
Great suggestion, it's been added, thank you!
