### ISSUE TITLE
metrica

### ISSUE THREAD

**Issue by adriancorrendo** [IdahoAgStats/ctv-agriculture#12]
1. Which package would you like to suggest? What features does it provide?
metrica is a compilation of more than 40 functions designed to evaluate prediction performance of point-forecast models (e.g. Machine Learning, APSIM, DSSAT) accounting for different aspects of the agreement between predicted and observed values. It includes error metrics (e.g. MAE, RMSE), model efficiencies (e.g. NSE, KGE), indices of agreement (e.g. d, RAC), goodness of fit (e.g. r, R2), concordance correlation (e.g. CCC), error decomposition (e.g. lack of accuracy-precision), and plots the visualize agreement. It also includes functions to open APSIM output files from APSIM Classic and APSIM NextGen.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=metrica

3. Which category do you think is the best fit for the package:

General Agriculture,
Agronomic Trials

**Comment by jpiaskowski** [comment]
This package looks really useful, thanks for the suggestion.  I'm wondering if it's a better fit for the "crop growth models" sub-section since it concerns APSIM and DSSAT models?

**Comment by adriancorrendo** [comment]
Sure, I just haven't found the "crop growth models" (although the package also servers for evaluating machine learning models as well). Thanks!

**Comment by jpiaskowski** [comment]
I updated the issue template to include this category.
