### ISSUE TITLE
Add landsepi

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#13]
1. Which package would you like to suggest? What features does it provide?

_landsepi_
A stochastic, spatially-explicit, demo-genetic model simulating the spread and evolution of a plant pathogen in a heterogeneous landscape to assess resistance deployment strategies. It is based on a spatial geometry for describing the landscape and allocation of different cultivars, a dispersal kernel for the dissemination of the pathogen, and a SEIR ('Susceptible-Exposed-Infectious-Removed’) structure with a discrete time step. It provides a useful tool to assess the performance of a wide range of deployment options with respect to their epidemiological, evolutionary and economic outcomes. 

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=landsepi

3. Which category do you think is the best fit for the package:

Plant Pathology

**Comment by jpiaskowski** [comment]
this package looks amazing! (and it's been added).
