### ISSUE TITLE
Add mvngGrAd

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#14]
1. Which package would you like to suggest? What features does it provide?
mvngGrAd
Package for moving grid adjustment in plant breeding field trials.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=mvngGrAd

3. Which category do you think is the best fit for the package:

Plant Breeding and Genetics

**Comment by jpiaskowski** [comment]
Done.
