### ISSUE TITLE
Add ALUES

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#15]
1. Which package would you like to suggest? What features does it provide?
ALUES: Agricultural Land Use Evaluation System

Evaluates land suitability for different crops production. The package is based on the Food and Agriculture Organization (FAO) and the International Rice Research Institute (IRRI) methodology for land evaluation. Development of ALUES is inspired by similar tool for land evaluation, Land Use Suitability Evaluation Tool (LUSET). The package uses fuzzy logic approach to evaluate land suitability of a particular area based on inputs such as rainfall, temperature, topography, and soil properties. The membership functions used for fuzzy modeling are the following: Triangular, Trapezoidal and Gaussian. The methods for computing the overall suitability of a particular area are also included, and these are the Minimum, Maximum and Average. Finally, ALUES is a highly optimized library with core algorithms written in C++.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=ALUES

3. Which category do you think is the best fit for the package:

General Agriculture

**Comment by jpiaskowski** [comment]
Done!
