### ISSUE TITLE
Add AgroReg

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#16]
1. Which package would you like to suggest? What features does it provide?
AgroReg
Linear and nonlinear regression analysis common in agricultural science articles (Archontoulis & Miguez (2015). <[doi:10.2134/agronj2012.0506](https://doi.org/10.2134%2Fagronj2012.0506)>). The package includes polynomial, exponential, gaussian, logistic, logarithmic, segmented, non-parametric models, among others. The functions return the model coefficients and their respective p values, coefficient of determination, root mean square error, AIC, BIC, as well as graphs with the equations automatically.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=AgroReg

3. Which category do you think is the best fit for the package:

Agronomic Trials (design and analysis)

**Comment by jpiaskowski** [comment]
Done!
