### ISSUE TITLE
What are the core packages? 

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/ctv-agriculture#17]
What constitute the most important packages for agriculture science, broadly speaking or discipline-specific. 

Feedback from twitter: 
https://twitter.com/SeedsAndBreeds/status/1529083494474735616

* Agricolae
* FedData, cdlTools, soilDB

**Comment by jpiaskowski** [comment]
no problem, just starting the thread! I'll work on this tomorrow.

**Comment by jpiaskowski** [comment]
Okay, here's my first start at it: 

agriCensData (for interval and censored data in agriculture)
Agridat (it has a very wide array of data sets and example analyses for each one)
agricolae (many standard functions for analyzing field trials)
qtl (standard qtl mapping)
sommer (wide array of mixed models)
AGHmatrix (every genomic relationship matrix)
rrBLUP (widely used, can be used for GWAS, genomic selection, regularized linear model)
drc (widely used package for dose response)

apsimx? 
DSSAT?
something for plant pathology?
something for entomology? 
Any recs on what to put for soil science @dylanbeaudette ? 

Honorable mention: ASReml (loads of people have suggested this, but it's not on CRAN or even open source)

**Comment by brownag** [comment]
RE: soil science @dylanbeaudette and I would suggest aqp -- Algorithms for Quantitative Pedology. This package, particularly the SoilProfileCollection class and related methods, is used extensively by soilDB. Some other packages that have been floated also use it (SISINTAR)

**Comment by dylanbeaudette** [comment]
Agreed, `aqp` would be a nice addition. I suspect that @pierreroudier has some additional suggestions.

**Comment by adamhsparks** [comment]
I can’t think of anything for plant pathology aside from Agricolae, which has AUDPC and AUDPS functions built in. That’s fairly general. The other packages are more specific

**Comment by jpiaskowski** [comment]
Current list:

agriCensData (for interval and censored data in agriculture)
Agridat (it has a very wide array of data sets and example analyses for each one)
agricolae (many standard functions for analyzing field trials)
qtl (standard qtl mapping)
sommer (wide array of mixed models)
AGHmatrix (every genomic relationship matrix)
rrBLUP (widely used, can be used for GWAS, genomic selection, regularized linear model)
drc (widely used package for dose response)
FedData (many federal data sources)
soilDB (NRCS soil db's)
cdlTools (cropscape datalayer)
apsimx (for crop modeling, unsure if it should be included)
DSSAT (for crop modelling, still unsure)
aqp (soil pedology functions)

**Comment by jpiaskowski** [comment]
New List:

agriCensData (for interval and censored data in agriculture)
Agridat (it has a very wide array of data sets and example analyses for each one)
agricolae (many standard functions for analyzing field trials)
qtl (standard qtl mapping)
sommer (wide array of mixed models)
AGHmatrix (every genomic relationship matrix)
drc (widely used package for dose response)
FedData (many federal data sources)
tidyUSDA (nass quick stats database)
soilDB (NRCS soil db's)
cdlTools (cropscape datalayer)
apsimx (for crop modeling, unsure if it should be included)
aqp (soil pedology functions)
inti (works with field book)
nlraa (tons of non-linear models for agriculture)
meteor (agrometeorological functionality)

Also, asreml cannot be included since it not available on CRAN, GitHub, or R-Forge.

**Comment by adamhsparks** [comment]
I've communicated with @palderman about DSSAT. His stats show roughly the same downloads for APSIMX and DSSAT, a few less but not that much more given the nature of the packages being so specific.

```r
library(tidyverse)
cranlogs::cran_downloads(packages = c("DSSAT", "apsimx"),
                         from = "2021-08-01",
                         to = "2022-07-31") %>%
  group_by(package) %>%
  summarize(count = sum(count))
#> # A tibble: 2 × 2
#>   package count
#>   <chr>   <dbl>
#> 1 apsimx   7964
#> 2 DSSAT    6342
```

Based on this, I'm inclined to keep it as a core package for crop modelling.

**Comment by jpiaskowski** [comment]
it's been added!
