### ISSUE TITLE
two misc packages suggested on twitter

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/ctv-agriculture#18]
PRISM: climate data (not sure if this on CRAN)
MoPBS: plant breeding simulation

**Comment by adamhsparks** [comment]
_prism_ is on CRAN, https://cran.r-project.org/web/packages/prism/index.html, but seems more general purpose weather and climate and not strictly ag related. If _rnoaa_ was removed, I'd suggest that this is not in-scope either.

**Comment by jpiaskowski** [comment]
agreed. MoPBS has been added.
