### ISSUE TITLE
Possible packages to include

### ISSUE THREAD

**Issue by kwstat** [IdahoAgStats/ctv-agriculture#2]
Not all of these are on CRAN, but here is a list to get started. Some of these are fringe or narrow-interest and should be deleted.

desplot is useful for plotting the plan for field experiments

agridat - datasets from agricultural experiments (mostly related to plant breeding)

### agriCensData
https://github.com/OnofriAndreaPG/agriCensData

Three datasets with censored observations for the paper "Analyzing interval-censored data in agricultural research: A review with examples and software tips".

### agriTutorial
https://myaseen208.github.io/agriTutorial/

Five datasets used to illustrate analyses.

### agricolae 

Has assorted data and functions for analysis of agricultural data.

### agroBioData
https://github.com/OnofriAndreaPG/agroBioData

Datasets for agriculture and applied biology.  Referenced by this blog: https://www.statforbiology.com/

### BGLR - Bayesian Generalized Linear Regression.

Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.

### BLR - Bayesian Linear Regression.

Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.

### BSagri

Safety assessment in agriculture trials

### cropcc - Climate change on crops
https://r-forge.r-project.org/projects/cropcc/

### drc - Dose response curves

Has nice herbicide dose response curves and germination data for mungbean, rice, wheat.

### FW - Finlay-Wilkinson regression
https://github.com/lian0090/FW/ 

Has phenotype data and marker data for 599 wheat lines in 4 environments.

### ggenealogy
https://www.jstatsoft.org/article/view/v089i13

Data `sbGeneal` contains a soybean pedigree with 230 varieties.

### gRbase 

Data `gRbase::carcass`: thickness of meat and fat on slaughter pigs

### lmDiallel
https://github.com/OnofriAndreaPG/lmDiallel/tree/master/data

### lmtest

Data `lmtest::ChickEgg` time series of annual chicken and egg production in the United States 1930-1983.

### nlraa

Miguez. Non-linear models in agriculture.
`nlraa::sm` = `agridat::miguez.biomass`
Vignettes and functions for working with (non)linear mixed models

   

### plantbreeding
https://r-forge.r-project.org/projects/plantbreeding/
```
Data: fulldial
Data: linetester
Data: peanut same as agridat::kang.peanut
```

### soilDB
https://ncss-tech.github.io/AQP/soilDB/soilDB-Intro.html
Soil database interface.

### sommer - Solving mixed model equations in R

Data: h2. Modest-sized GxE experiment in potato Data: cornHybrid. Yield/PLTHT for 100 hybrids from 20 inbred * 20 inbred, 4 locs. Phenotype and relationship matrix.

Data: wheatLines  CIMMYT wheat data for 599 lines. Phenotype and relationship data.

Data: RICE

Data: FDdata taken from agridat::bond.diallel

Data: Technow_data. AF=Additive Flint. AD=Additive Dent. MF=Marker Flint. MD=Marker Dent. pheno=phenotype data for 1254 hybrids (GY=yield, GM=moisture).  This data is from Technow et al:
http://www.genetics.org/content/197/4/1343.supplemental

### SoyNAM - Soybean nested association mapping 

Dataset with phenotype data 3 yr, 9 locations, 18 environments, 60 thousand observations for height, maturity, lodging, moisture, protein, oil, fiber, seed size. There are 5000+ strains, 40 families.

Data formatted for the analysis of the NAM package is available with the following command: `SoyNAM::ENV()`.

### spdep

Has a vignette 'The Problem of Spatial Autocorrelation: forty years on' that examines agriculture in Irish counties.
See also the data `ade4::irishdata`

### StatForBiology
https://www.statforbiology.com/

Blog posts with example analyses.

### statgenSTA
https://CRAN.R-project.org/package=statgenSTA
See vignette: Modeling field trials using statgenSTA

### statgenGWAS
https://CRAN.R-project.org/package=statgenGWAS

Includes a worked example with data from:
https://data.inra.fr/dataset.xhtml?persistentId=doi:10.15454/IASSTN 

### st4gi - Stat for genetic improvement
https://github.com/reyzaguirre/st4gi

**Comment by jpiaskowski** [comment]
Thanks, I'll add these in! I'm going to leave this issue open until I do that.
