### ISSUE TITLE
more packages

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/ctv-agriculture#20]
od
DiGGer

**Comment by jpiaskowski** [comment]
Suggestions originated on twitter. {od} is a spatial package and that does appear overly relevant to ag research. I cannot find "DiGGer" on CRAN, GitHub or general google search.

**Comment by adamhsparks** [comment]
DiGGer, http://www.nswdpibiom.org/austatgen/software/

**Comment by jpiaskowski** [comment]
added!
