### ISSUE TITLE
SISINTAR - Soil profiles from Argentina

### ISSUE THREAD

**Issue by yabellini** [IdahoAgStats/ctv-agriculture#21]
1. Which package would you like to suggest? What features does it provide?

https://github.com/INTA-Suelos/SISINTAR

Allow access to the soil profile of INTA in Argentina.  Also, allow handling of the soil data.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

There is not on CRAN (yet), but I suggest it because on the R-Ladies Community Slack was a request to suggest packages even if they aren't on CRAN.

3. Which category do you think is the best fit for the package:

Soil Science

**Comment by jpiaskowski** [comment]
This looks great, thank you! My Spanish is a bit weak, but this looks like a package for accessing a soil profile database for Argentina? Below is my proposed summary statement for it. Can you let me know if this is correct? Please feel free to edit as you see fit. 

> [SISINTAR][] provides access to [SiSINTA](http://sisinta.inta.gob.ar/) (Sistema de información de Suelos del INTA), a soil profile database for Argentina.

**Comment by yabellini** [comment]
Yes, that is correct!

**Comment by jpiaskowski** [comment]
Okay, I've added it to the "Agricultural databases" section (I don't think this was in the original template you used, which I have since updated). Thanks again.
