### ISSUE TITLE
AgroMet - Argentina agrometeorological data and index

### ISSUE THREAD

**Issue by yabellini** [IdahoAgStats/ctv-agriculture#22]
1. Which package would you like to suggest? What features does it provide?

The {agromet} package includes a series of functions to calculate climatic and hydrological indices and statistics from tidy data. For example, umbrales() allow counting the number of observations that meet a certain condition, and dias_promedios() returns the first and last day of the average year of occurrence of an event.

Other functions such as spi() work as wrappers of functions from other packages and are intended to be compatible with tidy data management.

Finally, the package includes a geo-referenced data plotting function map() with INTA's own style and logo.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:
It is not in CRAN, yet, but I suggest it because in the R-Ladies Slack was a request about packages related to agriculture even if not in CRAN.

https://github.com/AgRoMeteorologiaINTA/agromet

3. Which category do you think is the best fit for the package:

Agrometerology

**Comment by jpiaskowski** [comment]
Adding this involves adding a new category for "Agrometerology", which I think is a good idea. @adamhsparks and @janetw what do you think?

**Comment by adamhsparks** [comment]
Seems right as I know of at least one more example

**Comment by jpiaskowski** [comment]
We just got some feedback from the CTV committee to not include packages that are not ag specific. I've opened up a [request](https://github.com/cran-task-views/Hydrology/issues/113) to the hydrology CTV to add {agromet} to that.

**Comment by yabellini** [comment]
Why do you say this is not agricultural specific? I don't understand why you accept soil packages and not agrometeorology packages.

The measures and functions on the packages are of agricultural interest. Like Temperature and Humidity Index is used to determine heat stress in animals. 
The measurement of minimum temperature at ground level is of agronomic interest and for agronomic frosts affecting crops (and the function and calculations associated with this variable). 

That is why the name is agrometeorology (agricultural meteorology) and not only meteorology. In my country, it is a mandatory course in agronomy engineering and is one of the research disciplines in agronomy.

I would be very grateful for more details to understand if it is something regional or something about the language of the package or how it is presented.

**Comment by jpiaskowski** [comment]
There's no question that weather and agrometeorology are directly relevant to agriculture. There is a [concern](https://github.com/cran-task-views/ctv/issues/27) that this proposed CTV is too broad overall and hence will both be difficult to maintain and will overlap too much with existing task views. We kept the "agrometeorology" section, but also referred to the hydrology CTV as well, which lists many weather and climate-related packages.  It's a fuzzy line, but the thinking is that if the functions are general and not specific to ag (e.g. other environmental disciplines would find this useful), then the package belongs in hydrology. If it is ag-specific, then we can list it. 

If you think it belongs it the ag CTV, it can be re-added. This discipline is a bit outside my area of expertise, so I'm less certain how to proceed. It may get more exposure to be in another CTV and referenced by this one.

**Comment by jpiaskowski** [comment]
[pull request](https://github.com/cran-task-views/Hydrology/pull/115) made to the hydrology ctv to agromet.
