### ISSUE TITLE
Add ag5Tools

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#25]
1. Which package would you like to suggest? What features does it provide?

ag5Tools

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=ag5Tools

3. Which category do you think is the best fit for the package:   

* General Packages   
  * Agricultural data sets  

I think this is the most appropriate for it, but am open for discussion, so I didn't make this one a PR

**Comment by jpiaskowski** [comment]
It looks like it's accessing an API, so how about "Agricultural & land use databases"? Or Agrometerology.

**Comment by adamhsparks** [comment]
Let's go with "Agrometerology"
