### ISSUE TITLE
Add nasapower?

### ISSUE THREAD

**Issue by adamhsparks** [IdahoAgStats/ctv-agriculture#26]
1. Which package would you like to suggest? What features does it provide?

*nasapower*, a client for 'NASA' 'POWER' global meteorology, surface solar energy and climatology data 'API'. 'POWER' (Prediction Of Worldwide Energy Resource) data are freely available for download with varying spatial resolutions dependent on the original data and with several temporal resolutions depending on the POWER parameter and community.

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=nasapower

3. Which category do you think is the best fit for the package:   

*(Delete those categories which do not apply)*

* General Packages
  * Agrometeorology

If we have *rnoaa* back in the mix, I'd suggest this one as well. The *APSIMX* package already has it as a dependency. It has a specific "Ag" community with weather and climate parameters for agrometeorology, which is why I wrote the package to start with.

**Comment by jpiaskowski** [comment]
We just got some feedback from the CTV committee to not packages unless they are ag specific. Can you request it be added to the hydrology CTV?

**Comment by adamhsparks** [comment]
OK
