### ISSUE TITLE
Add AlphaSimR 

### ISSUE THREAD

**Issue by gregorgorjanc** [IdahoAgStats/ctv-agriculture#9]
1. Which package would you like to suggest? What features does it provide?

AlphaSimR for quantitative genetics and breeding simulations 

2. Please provide the link to CRAN by appending the package name
(case-sensitive) to the end of the URL below:

https://cran.r-project.org/package=AlphaSimR

3. Which category do you think is the best fit for the package:

General Agriculture,
Soil Science,
Agronomic Trials,
* Plant Breeding and Genetics,
Entomology,
Animal Science,
Food Science,
Rural Sociology,
Agricultural Economics

**Comment by jpiaskowski** [comment]
Done, thanks for suggestion. What a cool package!
